CREATE TABLE `BlogPost` (
  `id` VARCHAR(191) NOT NULL,
  `publicId` VARCHAR(191) NOT NULL,
  `authorId` VARCHAR(191) NULL,
  `title` VARCHAR(180) NOT NULL,
  `slug` VARCHAR(180) NOT NULL,
  `excerpt` VARCHAR(500) NOT NULL,
  `body` LONGTEXT NOT NULL,
  `coverImageUrl` VARCHAR(1000) NULL,
  `coverImageAlt` VARCHAR(240) NULL,
  `seoTitle` VARCHAR(180) NULL,
  `seoDescription` VARCHAR(320) NULL,
  `status` ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT',
  `publishedAt` DATETIME(3) NULL,
  `archivedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `BlogPost_publicId_key`(`publicId`),
  UNIQUE INDEX `BlogPost_slug_key`(`slug`),
  INDEX `BlogPost_status_publishedAt_idx`(`status`, `publishedAt`),
  INDEX `BlogPost_updatedAt_idx`(`updatedAt`),
  CONSTRAINT `BlogPost_authorId_fkey` FOREIGN KEY (`authorId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
